# Generated by Django 4.2.25 on 2025-11-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesubmission',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
