# Generated by Django 4.2.25 on 2025-11-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_timesubmission_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesubmission',
            name='is_approved',
        ),
    ]
